export const AboutData = {
  primary: false,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "About us",
  headline: "Tanzeel Group LTD",
  headline_2: "Company No 09761578",
  headline_3: "Registered in England",
  description: `We help business owners increase their revenue.We provide best temporary workers for your business`,
  buttonLabel: "contact us",
  imgStart: "start",
  img: require("../../images/about.jpg"),
  alt: "Vault",
  start: "true",
};
